-- Flyway migration: initial schema for affiliates
-- Compatible with H2 and PostgreSQL

CREATE TABLE IF NOT EXISTS affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(100) UNIQUE,
    salary NUMERIC(19,2) NOT NULL,
    registration_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_affiliates_document ON affiliates(document);
CREATE INDEX IF NOT EXISTS idx_affiliates_status ON affiliates(status);
